server:
  bind_address: 127.0.0.1
  port: 9000
  format: html

database:
  path: ./data/data.db

tracker:
  history:
    source: virtualdj
    path: C:\Users\ewenb\AppData\Local\VirtualDJ\History
  source:
    paths:
      - C:\Users\ewenb\Music\Musiques de fond
      - C:\Users\ewenb\Music\Evyntia
