server:
  bind_address: 127.0.0.1
  port: 9000

database:
  path: ./data/data.db

tracker:
  history:
    path: C:\Users\ewenb\AppData\Local\VirtualDJ\History\tracklist.txt
  source:
    paths:
      - C:\Users\ewenb\Music\Musiques de fond
      - C:\Users\ewenb\Music\Evyntia
